### ISSUE TITLE
Add run instructions to the README

### ISSUE THREAD

**Issue by egonw** [cheminfo/wikipedia#13]
Please add some pointers to the README, e.g. in what order scripts should be called. I found the "dump/all.sh", but cannot get that to work, and am wondering if there is another script that I should run first...

**Comment by targos** [comment]
The scripts in the "dump" and "node" directories are for maintenance of the project. It is not required to run them in order to use the website (Eveything is self-contained in the "site" directory). I will add section in the README to clarify that.

**Comment by egonw** [comment]
Oh, just for clarity... I am interested in the whole process, not just the website :)
