### ISSUE TITLE
dump/all.sh does not work well on Debian GNU/Linux (Testing)

### ISSUE THREAD

**Issue by egonw** [cheminfo/wikipedia#14]
I have the following NodeJS packages installed:

nodejs                       0.10.29~dfsg-1.1
npm                          1.4.21+ds-2
node-promise                 5.0.0-1

The "npm update" seems to run well:

    $ npm update
    ms@0.6.2 node_modules/superagent/node_modules/debug/node_modules/ms
    methods@1.0.1 node_modules/superagent/node_modules/methods
    component-emitter@1.1.2 node_modules/superagent/node_modules/component-emitter
    extend@1.2.1 node_modules/superagent/node_modules/extend
    qs@1.2.0 node_modules/superagent/node_modules/qs
    mime@1.2.11 node_modules/superagent/node_modules/mime
    formidable@1.0.14 node_modules/superagent/node_modules/formidable
    readable-stream@1.0.27-1 node_modules/superagent/node_modules/readable-stream
    ├── isarray@0.0.1
    ├── inherits@2.0.1
    ├── string_decoder@0.10.31
    └── core-util-is@1.0.1
    form-data@0.1.3 node_modules/superagent/node_modules/form-data
    ├── async@0.9.0
    └── combined-stream@0.0.7 (delayed-stream@0.0.5)

But the next command in the all.sh does not work. I guess I should replace node with nodejs on my system (as 'node' was an executable name used in another package), but I get this error:

    $ nodejs wiki.js ids
    
      wiki-ids(1) does not exist, try --help

When I run wiki-ids.js, I get an error about "new Promise":

    $ nodejs wiki-ids.js ids
    Getting page ids
    
    /home/egonw/var/Projects/GitHub/wikipedia/dump/util.js:5
        return new Promise(function (resolve, reject) {
                   ^
    ReferenceError: Promise is not defined
        at Object.exports.request (/home/egonw/var/Projects/GitHub/wikipedia/dump/util.js:5:16)
        at getList (/home/egonw/var/Projects/GitHub/wikipedia/dump/wiki-ids.js:57:17)
        at getForTemplate (/home/egonw/var/Projects/GitHub/wikipedia/dump/wiki-ids.js:30:12)
        at Object.<anonymous> (/home/egonw/var/Projects/GitHub/wikipedia/dump/wiki-ids.js:10:1)
        at Module._compile (module.js:456:26)
        at Object.Module._extensions..js (module.js:474:10)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:312:12)
        at Function.Module.runMain (module.js:497:10)
        at startup (node.js:119:16)

**Comment by targos** [comment]
The dump scripts are only compatible with Node.js v0.12.x or io.js. The Promise API is not available in the 0.10 branch.
There is a useful tool to manage versions of node on Unix systems  : [nvm](https://github.com/creationix/nvm)

Anyway, I do not recommend to execute all.sh. It only used by our server for the automatic daily process of updating and publishing the data.

I added a dump.sh that does only the interesting part.
All the files generated by the scripts are put in the dump/data directory.

**Comment by egonw** [comment]
OK, thanks! A note in the README with needing NodeJS >= 0.12 could be helpful.

**Comment by egonw** [comment]
Confirmed working well with NodeJS 0.12.
