### ISSUE TITLE
Better Wikipedia article rendering

### ISSUE THREAD

**Issue by kelson42** [cheminfo/wikipedia#21]
//molecule.link = 'http://en.wikipedia.org/w/index.php?printable=yes&title=' + molecule.code;                                                                                            
molecule.link = 'http://rest.wikimedia.org/en.wikipedia.org/v1/page/html/' + molecule.code;

**Comment by targos** [comment]
done! 
thank you @kelson42

**Comment by lpatiny** [comment]
@kelson42
I could not find a way to remove the space on the left. In the CSS there is a margin-left of 10em. Do you know how to deal with this ?
media screen .mw-body {  margin-left: 10em;

**Comment by kelson42** [comment]
I have tried myself to do this by tunning the iframe margin, without success. The best approach is probably to tweak the iframe content DOM via a small js function triggered at the end of the content load. Such solution would also allow to remove the red/blue links which, in the such a context, are IMO not welcomed.

**Comment by kelson42** [comment]
People behind rest.wikimedia.org want to fix that problem too. Here is the corresponding ticket https://phabricator.wikimedia.org/T68461. I recommend to subscribe to it and award a token to show your interest.

**Comment by lpatiny** [comment]
Because we use an IFRAME that access directly to the wikipedia server I don't see how we could tweak the content to remove the links and the margin. A javascript present outside the IFRAME should not be able to access the content of the iframe due to XSS protection no ? How would you implement this ?

**Comment by kelson42** [comment]
@lpatiny 
Yes, you are right :( But still not 100% convinced there is no workaround...

**Comment by targos** [comment]
Fixed by fetching the html content and using URL.createObjectURL instead of directly the wikimedia link
