### ISSUE TITLE
Make Cheminfo mobile friendly

### ISSUE THREAD

**Issue by kelson42** [cheminfo/wikipedia#25]
Cheminfo, because of the technology choices, should work out-of-the box on mobile devices. Unfortunately, this is not really the case. The reason is that the user interface is thought for high screen resolutions and does not display "correctly" on smaller screens (see screenshots).

![screen shot 2015-04-24 at 15 06 52](https://cloud.githubusercontent.com/assets/1029718/7319237/4d1a3fee-ea94-11e4-9361-734866bf9125.png)

The HTML/CSS should be customized, following "responsive design" guidelines, to be able to offer a similar user experience on "any kind" of screen size.

**Comment by peter-ertl** [comment]
I am not sure whether making the full Wikipedia search site mobile friendly is possible at all. The on-line search engine has relatively high requirements on computer processing power and also most mobile web browsers do not have all required HTML5 features (my Samsung Galaxy Tab 10.1 definitely does not). 
Possible solution would be to make a "search light". Just draw query with JSME (this runs on mobile devices and iPhone etc), submit search, get back list of molecules and select one to see the WP page.
This is of course not so elegant as the on-line search, but would open wealth of WP chemistry to mobile users.

**Comment by kelson42** [comment]
The question of outdated web browsers is a serious question but it's not really mobile related IMO Like for desktop computers, it's possible for anybody to download an modern browser on Android (for example Firefox).

I would tend to make a similar answer concerning the hardware performances: this "problem" goes a little bit beyond the topic of this ticket.

The problem I wanted to report here is that, as a user, even if you have a top mobile browser & and a top mobile device, you still have a problem to use cheminfo.

PS: I prefer to not talk about JSM*, this is a bad word in my vocabulary ;)
