### ISSUE TITLE
Allow to save locally new widgets/dashboards/...

### ISSUE THREAD

**Issue by kelson42** [cheminfo/wikipedia#27]
It seems that the Cheminfo saves user related information on the HTTP server, ie. in a remote "couchDB" database. This approach is not compatible with an offline version. I think we need here a new kind of backend allowing the web engine to save data locally (cookies?)

**Comment by lpatiny** [comment]
This is only used for development of a new view. The visualizer itself required a viewURL that points towards a JSON file that contains the description (arrangement of the modules) of the view. Therefore once the development of the view is done you can simply copy / paste this JSON to any static file.  In this project the idea is not that the user creates new view so it is not an issue.

**Comment by kelson42** [comment]
Does that means the ability to develop new widgets would be limited to the online version? Assuming we would find a solution to replace couchdb with a local/clientside storage, would that be enough to get this feature working *also offline*?

**Comment by targos** [comment]
I think this issue is beyond the wikipedia project. We should move the conversation to the main repository: [npellet/visualizer](https://github.com/npellet/visualizer)
