### ISSUE TITLE
change the commit text

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/wikipedia#30]
Would be nice if int the commit text when updating data we get the information like

molecules:13993, errors:448, nogood:333, notfound:2179, dup:587

It would allow to easily follow the evolution of wikipedia

**Comment by targos** [comment]
is https://github.com/cheminfo/wikipedia/blob/master/stats.json not enough ?

**Comment by targos** [comment]
See https://github.com/cheminfo/wikipedia/commit/bdf700422bd69f9fdd72603622c1a7e23dcfc633 for a tentative of amelioration:

![image](https://cloud.githubusercontent.com/assets/2352663/17897131/550bdcbe-6953-11e6-821b-665ed159f810.png)

**Comment by targos** [comment]
ping @lpatiny. It's been around for 1 week now: https://github.com/cheminfo/wikipedia/commits/master

**Comment by lpatiny** [comment]
Yes we may close the ticket. I guess there should be a API that allows to retrieve the commit messages and generate charts automatically from a view.

**Comment by targos** [comment]
https://github.com/cheminfo/wikipedia/blob/master/stats.json should be enough. It has the same data
