### ISSUE TITLE
SMILES parsing error is not available

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/wikipedia#43]
Mounia told me that currently in the data.json the errors do not contain the error message

```
],"errors":[
{"id":3370,"smiles":"[BH-]1=[nH+][B-]2=[nH+][BH-]=[n+]3[BH-]=[nH+][B-]4=[nH+][BH-]=[n+]5[BH-]=[nH+][B-]6=[nH+][BH-]=[n+]1[B-]7=[n+]2[B-]3=[n+]4[B-]5=[n+]67"},
{"id":6016,"smiles":"O=C1Nccc(N)n1"},
{"id":12439,"smiles":"O=C1c2ncnc2nc(N)N1"},
```

@targos I'm wondering what is `e.f`. Should this not be `e.toString()` ?

https://github.com/cheminfo/wikipedia/blob/8dafe09dba87cdea2da053be527c45e1c132cb98/dump/wiki-parse.js#L151-L157

**Comment by targos** [comment]
The code generated by GWT probably changed at some point. Fixing...
