### ISSUE TITLE
Title and number of molecules

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/wikipedia#46]
In this module

![image](https://user-images.githubusercontent.com/1484241/210797572-59e5a66d-d8d9-4c26-976c-02ac6ae5120d.png)

Could we add a title "Selected list of molecules" and the number of selected molecules ? (123/15123)

We should display the currently selected molecules as well as the total number.

**Comment by stropitek** [comment]
@lpatiny I think you are referring to molecules "shown" or "matching" but not "selected"
