### ISSUE TITLE
Add molecule editor help

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/wikipedia#82]
Just after Draw a structure add a question mark that will open a Help dialog

![image](https://github.com/cheminfo/wikipedia/assets/1484241/b9c1555c-1a55-458f-beed-527d8e81479c)

The dialog box will contain:

~[help.zip](https://github.com/cheminfo/wikipedia/files/11912514/help.zip)~

The result can be found here (but should look better):

~https://www.lactame.com/visualizer/v2.154.1/modules/types/science/chemistry/ocl_editor/help/index.html~

**Comment by targos** [comment]
Did you make `help.zip` from this link?

The help at https://github.com/Actelion/openchemlib/tree/master/src/main/resources/html/editor might be more up-to-date.

**Comment by targos** [comment]
@moonayyur After discussion with Luc, we should use the latest help from https://github.com/Actelion/openchemlib/tree/master/src/main/resources/html/editor

**Comment by lpatiny** [comment]
You may use this zip corresponding to Michael link.

[editor.zip](https://github.com/cheminfo/wikipedia/files/11925404/editor.zip)

**Comment by targos** [comment]
If possible, use the HTML file so that we can easily update it.
If not, please document how to make the conversion to React.
