### ISSUE TITLE
Error in uploading codecov

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/wikipedia#96]
@targos 

Since couple of days we have an error in the build:

https://github.com/cheminfo/wikipedia/actions/runs/12023404078/job/33517223619#step:7:177

Could you have a look ?

**Comment by targos** [comment]
Either we run Vitest with coverage enabled, or we disable coverage upload. I suggest the second option.

**Comment by lpatiny** [comment]
Yes indeed we can disable coverage.
